### ISSUE TITLE
Additional Visualization

### ISSUE THREAD

**Issue by A-Guldborg** [WilliamHeidemann/GitInsight#117]
Implement an analysis and visualization of your choice in your GitInsight applications. For example, you might want to identify and present those files that change most often/least often, those files that change most often together (i.e., they appear in commits together, which is called logical coupling), identify groups of authors that work often on the same files, etc.

Make sure that the new features and analyses are covered by appropriate tests in your test suites.

**NOTE**
Can be separated into frontend + backend when a decision of what visualization and which data structures are necessary has been made.

**Comment by MadsRoager** [comment]
#127 Basic visual representation
