### ISSUE TITLE
Implement persistent storage with Entity Framework

### ISSUE THREAD

**Issue by OliFryser** [WilliamHeidemann/GitInsight#18]

**Comment by A-Guldborg** [comment]
#26 implements this. At this point in time, inmemory database for testing has been implemented and the required functionality using dependency injection for the database works. 

Todo: Add MSSQL to the actual GitInsight application

**Comment by A-Guldborg** [comment]
We need to consider how we want to implement the database for the application, because we might need the user to setup a local database for this to work using dotnet secrets or similar.
