### ISSUE TITLE
Web data retrieval

### ISSUE THREAD

**Issue by A-Guldborg** [WilliamHeidemann/GitInsight#80]
Prerequitesites: #79 #52 

Add a front-end web-application that you write with .Net Blazor (WebAssembly) to your already existing applications. That front-end application interacts with your GitInsight back-end application via the REST API that you implemented last week.

The front-end application should be able to receive the identifier of a GitHub repository (<github_user>/<repository_name> or <github_organization>/<repository_name> as described for last week, see above) via a suitable input field.

The data will be visualized in another issue.

**Comment by MadsRoager** [comment]
#115 Basic implementation

**Comment by A-Guldborg** [comment]
This includes refactoring `BlazorApp` to `GitInsight.BlazorApp`

Preferably also remove all `warnings` from compile time in the `BlazorApp`
