### ISSUE TITLE
Collect Github Forks

### ISSUE THREAD

**Issue by A-Guldborg** [WilliamHeidemann/GitInsight#82]
Additionally, in your GitInsight back-end applications implement a new analysis. It should be able to list all forks of a repository on GitHub. To do so, it should call the [GitHub REST API](https://docs.github.com/en/rest) and [collect a list of all forks from a given repository](https://docs.github.com/en/rest/repos/forks#list-forks). That is, when your GitInsight REST API receives a GET request with a GitHub repository identifier of the form <github_user>/<repository_name> or <github_organization>/<repository_name>, then besides the two already existing analyses of cloned Git repositories your application contacts the GitHub REST API to collect the number of forks of that repository.

To connect to the GitHub REST API, you need an Access Token. Read [this documentation](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token) on how to receive an Access Token for the GitHub REST API. Remember and double check on how Rasmus demonstrated to handle secrets like access tokens in .Net projects. That is, do not store the access token directly in your source code. It should never end up in your source code repository that is publicly shared with the world.

**Comment by OliFryser** [comment]
#100 
#99
